name: Publish to PyPI

on:
  push:
    branches:
      - main

jobs:
  pypi-publish:
    name: Build and Publish Release
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/ingestion-lib
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Poetry install
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --with dev --sync

      - name: Python Semantic Release
        uses: python-semantic-release/python-semantic-release@v8.0.8
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build library
        run: |
          poetry build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
