name: Upload Development Version

on:
  push:
    branches:
      - dev

jobs:
  upload-dev-version:
    environment:
      name: testpypi
      url: https://test.pypi.org/p/ingestion-lib
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Determine version with semantic-release
        run: semantic-release prerelease

      - name: Build library
        run: |
          poetry build

      - name: Publish package distributions to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
