name: Upload Development Version

on:
  push:
    branches:
      - dev

jobs:
  upload-dev-version:
    environment:
      name: testpypi
      url: https://test.pypi.org/p/ingestion-lib

    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel

      - name: Check commit message
        id: commit-check
        run: |
          commit_message=$(git log -1 --pretty=%B)
          echo "Commit message: $commit_message"
          if [[ "$commit_message" =~ ^(feat|fix): ]]; then
            echo "::set-output name=should_upload::true"
          else
            echo "::set-output name=should_upload::false"
          fi

      - name: Build library
        if: steps.commit-check.outputs.should_upload == 'true'
        run: |
          python setup.py sdist bdist_wheel

      - name: Publish package distributions to TestPyPI
        if: steps.commit-check.outputs.should_upload == 'true'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
